language: php

php:
  - 7.3

before_install:
  - touch ./database/database.sqlite

install:
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction
  - php artisan key:generate --force
  - php artisan migrate --seed --force

script:
  - phpunit
  - phpunit --group hits-stripe

notifications:
  email: false
